// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlA4n4FiNVCUuXWP2LwzaKXCh07uA_8M',
    appId: '1:990242303280:web:9b00960e8fd82a9d372cf5',
    messagingSenderId: '990242303280',
    projectId: 'enigmaweb-82979',
    authDomain: 'enigmaweb-82979.firebaseapp.com',
    storageBucket: 'enigmaweb-82979.firebasestorage.app',
    measurementId: 'G-J7EWW6RFBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEmY6J0_IBNA-z9kixpMNiECYzk17yK3s',
    appId: '1:990242303280:android:7ffdc5494159d145372cf5',
    messagingSenderId: '990242303280',
    projectId: 'enigmaweb-82979',
    storageBucket: 'enigmaweb-82979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhMNxofUMT7TiipqAIxjy2dGFf2ybdDA',
    appId: '1:990242303280:ios:e05778e6e12ad8dd372cf5',
    messagingSenderId: '990242303280',
    projectId: 'enigmaweb-82979',
    storageBucket: 'enigmaweb-82979.firebasestorage.app',
    iosBundleId: 'com.example.oenigama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhMNxofUMT7TiipqAIxjy2dGFf2ybdDA',
    appId: '1:990242303280:ios:e05778e6e12ad8dd372cf5',
    messagingSenderId: '990242303280',
    projectId: 'enigmaweb-82979',
    storageBucket: 'enigmaweb-82979.firebasestorage.app',
    iosBundleId: 'com.example.oenigama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKlA4n4FiNVCUuXWP2LwzaKXCh07uA_8M',
    appId: '1:990242303280:web:c093973a945686cf372cf5',
    messagingSenderId: '990242303280',
    projectId: 'enigmaweb-82979',
    authDomain: 'enigmaweb-82979.firebaseapp.com',
    storageBucket: 'enigmaweb-82979.firebasestorage.app',
    measurementId: 'G-JJWCN3143E',
  );

}